# SimNet Training Configuration

# Model architecture
model:
  hidden_dims: [128, 128, 128]
  learning_rate: 0.001
  dropout_rate: 0.3
  activation: "relu"
  layer_norm: true

# Training data collection
data_collection:
  physics_samples: 200000
  real_samples: 10000
  noise_std: 0.1
  validation_split: 0.1
  random_seed: 42

# Training parameters
training:
  # Physics-based pretraining
  pretrain:
    epochs: 50
    batch_size: 512
    early_stopping_patience: 10
    reduce_lr_patience: 5
    reduce_lr_factor: 0.5
    min_lr: 0.00001

  # Real-data fine-tuning
  finetune:
    epochs: 20
    batch_size: 128
    early_stopping_patience: 5
    reduce_lr_patience: 3
    reduce_lr_factor: 0.5
    min_lr: 0.00001

# Hybrid simulation settings
hybrid:
  initial_ratio: 0.0
  target_ratio: 1.0
  adaptation_steps: 1000
  adaptation_schedule: "linear"  # or "exponential"

# Logging
logging:
  log_frequency: 1
  validation_frequency: 5
  save_best: true
  save_frequency: 10
